language: ruby

script:
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - bundle exec rake

rvm:
  - 1.27.0
notifications:
  email:
    recipients:
      - kleberbritomoreira10@gmail.com
    on_success: always
      
branches:
  only:

    - master
    - travis
