language: ruby
script:
- bundle install
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake db:seed
- bundle exec rake
rvm:
- 2.1.0
notifications:
  email:
    recipients:
    - kleberbritomoreira10@gmail.com
    - kleber_kbm@hotmail.com
    - Gustavo.sabino@hotmail.com
    on_success: always
deploy:
  provider: heroku
  api_key:
    secure: UtRxHYEhu52xOj2+pIHgG3ZJuR97YczazKx6hT3tMdejI9WSqy3Pw2NaGKmYPEGifAIUjTMqLQb9AFLtB3oNibO8i3syubDI7QyFKXEKpvdCi0Q7aFJKqkA860klu+4a0Gy2R41SIoS8S2XRySvtGAxP5HYhBN6ihPHN372riW/dlEkiL4hPQrubE8BB14l+NZ0EUOFlXOaCMGER/rBTDGhL21KhY1VdhhXLTi3Ub4LgHsAsiFpYgX0H5AZTFc+aEbLYkaa4FJvk+8ri4JVQtieOHLX6jbjMMN1a6sECG3LyiAmOVqXZoO+eeFwtetDVc/gmc7PkFNRltYP6N3ceM4mvHZrlBedIXxlxAjK842I95M281rLR+9u8gmF0vOPzMAicAMOdvQzZYmzkW4BTtY5iKsANOWPhAoR646rfpjXgKJwGNjPGsX36GawQYHkhgUQaFcg+DQETK5n4d0nLKV1FQyr8lUVjn8FABDUVo+oYMZqmf5ve5P39OxJQBSrwZD8a1ESTWvgLu4lOqLfEf2WmsKyI3OqUB6thr7GEZcYHSOpzWruXsZXtUbKBPqoF7LrMpMVrMZykIGn91gsCQXeI9SxhvBCTDBw8bcKj0pGMSYsNT2cowoc/HdnGGXfs38PyW3LWO3Q3EHeA5+WHtktExCvx2xH4Ejch3wx08AY=
  app: sct-app
  on:
    repo: kleberbritomoreira10/GCS---SCT
