language: ruby

script:
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - bundle exec rake

rvm:
  - 2.1.0
notifications:
  email:
    recipients:
      - kleberbritomoreira10@gmail.com
      - kleber_kbm@hotmail.com
    on_success: always  
branches:
  only:

    - master
    - action
