language: ruby

script:
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - bundle exec rake

rvm:
  - 2.1.0
notifications:
  email:
    recipients:
      - kleberbritomoreira10@gmail.com
      - kleber_kbm@hotmail.com
      - Gustavo.sabino@hotmail.com
    on_success: always  

after_success:
  - "bundle exec cap deploy"

deploy:
  provider: heroku
  api_key: c2df1f32-326f-44a9-b41a-6729054f4002
  on: 
    all_branches: true